In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import joblib
from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics import accuracy_score,classification_report
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier

In [5]:
# vectorizer=joblib.load(r"C:\Users\Karan Brar\Desktop\New folder\Language_Detection\models\vectorizer.pkl")

In [6]:
le=LabelEncoder()

In [7]:
data=pd.read_csv(r"C:\Users\Karan Brar\Desktop\New folder\Sentiment_Analyzer\data\new_train.csv")


In [8]:
text=data['text']
text=text.fillna("")
y=data['sentiment']
y=y.dropna()


In [9]:
print(text.count())
print(y.count())

27481
27481


In [10]:
vectorizer=TfidfVectorizer(analyzer='char',ngram_range=(1,5))
X=vectorizer.fit_transform(text)

In [11]:
y_encoded=le.fit_transform(y)

In [12]:
model=MultinomialNB()

In [13]:
X_train, X_test, y_train, y_test=train_test_split(X,y_encoded,train_size=0.8)

In [14]:
model.fit(X_train,y_train)

MultinomialNB()

In [15]:
y_pred=model.predict(X_test)

In [16]:
print(y_pred)

[1 1 1 ... 1 1 1]


In [17]:
print(accuracy_score(y_pred,y_test))

0.5537565945060943


In [18]:
print(X_train)
print(y_train)


<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 5690157 stored elements and shape (21984, 340970)>
  Coords	Values
  (0, 5)	0.1790399283163123
  (0, 172324)	0.030457867469955886
  (0, 114133)	0.03555532313924305
  (0, 161628)	0.0750761240911045
  (0, 79753)	0.06053903523864831
  (0, 316828)	0.018526487042888073
  (0, 124661)	0.04953246445962243
  (0, 262069)	0.04362430639048092
  (0, 277544)	0.03156425501187625
  (0, 234047)	0.07934730078915721
  (0, 218588)	0.02080388819504682
  (0, 39937)	0.045857325363624475
  (0, 320109)	0.025801732615264746
  (0, 16618)	0.02782690491858075
  (0, 114134)	0.016026291395950305
  (0, 15759)	0.05027147414364246
  (0, 164380)	0.03530555045971872
  (0, 97209)	0.027985578397750146
  (0, 317803)	0.02071694395214746
  (0, 124662)	0.03708508448277545
  (0, 23447)	0.025139367581353073
  (0, 267868)	0.017770348224066868
  (0, 244048)	0.018191219355610324
  (0, 39938)	0.04639865015723272
  (0, 27944)	0.03192566446782933
  :	:
  (21983, 167234)	0.1

In [19]:
#Encode labels and train model again. Try diff models 

In [20]:
print(y_encoded)
print(np.unique(y_encoded))
print(le.classes_)

[1 0 0 ... 2 2 1]
[0 1 2]
['negative' 'neutral' 'positive']


In [31]:
from xgboost import XGBClassifier

clf = XGBClassifier(
    objective="multi:softmax",    # outputs class label directly
    num_class=3,                  # set number of classes explicitly (e.g., 3 classes)
    eval_metric="mlogloss",       # good for multi-class classification
    use_label_encoder=False,
    random_state=42,
    
    # 🔑 Hyperparameters to improve accuracy
    n_estimators=500,             # more boosting rounds
    learning_rate=0.05,           # smaller step size for better generalization
    max_depth=6,                  # controls complexity of trees
    subsample=0.8,                # use 80% of data for each boosting round
    colsample_bytree=0.8,         # use 80% of features for each tree
    reg_lambda=1.0,               # L2 regularization (helps avoid overfitting)
    gamma=1,                      # minimum loss reduction (makes splits more conservative)
    min_child_weight=3            # minimum sum of instance weights (avoids overfitting small samples)
)


In [32]:
clf.fit(X_train,y_train)

c:\Users\Karan Brar\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:183: UserWarning: [13:48:27] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)


XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='mlogloss',
              feature_types=None, feature_weights=None, gamma=1,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=3, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None, num_class=3, ...)

In [34]:
y_pred=clf.predict(X_test)
print(accuracy_score(y_pred,y_test))

0.7102055666727306


In [24]:
randforrest=RandomForestClassifier(n_estimators=100,random_state=42)


In [25]:
randforrest.fit(X_train,y_train)

RandomForestClassifier(random_state=42)

In [26]:
y_pred=randforrest.predict(X_test)

In [27]:
print(accuracy_score(y_pred,y_test))

0.6676368928506458


In [30]:
from sklearn.svm import LinearSVC
svm=LinearSVC(C=1.0)
svm.fit(X_train,y_train)
y_pred5=svm.predict(X_test)
print(accuracy_score(y_pred,y_test))

0.6676368928506458
